### ISSUE TITLE
Delete API call doesn't work

### ISSUE THREAD

**Issue by zutherb** [magneticio/vamp-core#13] opened 2015-08-14 05:40 UTC
I am using Vamp 0.7.9 and try to undeploy a deployment in Vamp UI but i got a 400.

<img width="1440" alt="screen shot 2015-08-14 at 07 33 13" src="https://cloud.githubusercontent.com/assets/489474/9267865/c30a847e-4256-11e5-9549-6280580d46be.png">

Then i try to delete the deployment by curl but i doesn't work as well.

```bash
 curl -v -X DELETE -H "Content-Type: application/json" DELETE http://172.31.1.11:8081/api/v1/deployments/e61c74c8-484d-4ce8-85fc-f8c3f27b4abc | gunzip -
* Rebuilt URL to: DELETE/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: DELETE
* Closing connection 0
curl: (6) Could not resolve host: DELETE
*   Trying 172.31.1.11...
* Connected to 172.31.1.11 (172.31.1.11) port 8081 (#1)
> DELETE /api/v1/deployments/e61c74c8-484d-4ce8-85fc-f8c3f27b4abc HTTP/1.1
> Host: 172.31.1.11:8081
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 202 Accepted
< Date: Fri, 14 Aug 2015 05:37:22 GMT
< Cache-Control: no-store
< Pragma: no-cache
< Access-Control-Allow-Origin: *
< Content-Encoding: gzip
< Content-Type: application/json; charset=UTF-8
< Content-Length: 1090
< 
{ [1090 bytes data]
100  1090  100  1090    0     0  18629      0 --:--:-- --:--:-- --:--:-- 18629
* Connection #1 to host 172.31.1.11 left intact
{"name":"e61c74c8-484d-4ce8-85fc-f8c3f27b4abc","endpoints":{"catalog.port":"9050"},"clusters":{"cart":{"services":[{"state":{"name":"ReadyForUndeployment","started_at":"2015-08-13T14:48:06.555-07:00"},"breed":{"name":"cart","deployable":"docker://zutherb/cart-service:latest","ports":{"port":"18100/http"},"environment_variables":{"REDIS_PORT_6379_TCP_ADDR":"$redis.host","REDIS_PORT_6379_TCP_PORT":"$redis.ports.port"},"constants":{},"dependencies":{"redis":{"name":"redis"}}},"scale":{"cpu":0.1,"memory":128.0,"instances":1},"routing":{"weight":100,"filters":[]},"servers":[{"name":"e61c74c8-484d-4ce8-85fc-f8c3f27b4abc_cart.3088f8d3-40fb-11e5-9157-56847afe9799","host":"172.31.2.11","ports":{"18100":31967},"deployed":true}],"dependencies":{"redis":"redis"},"dialects":{}}],"routes":{"18100":33004},"dialects":{}},"navigation":{"services":[{"state":{"name":"Error","started_at":"2015-08-13T22:03:51.26-07:00","notification":"Deployment service error was not restored.  Problem in cluster navigation, with a service containing breed navigation."},"breed":{"name":"navigation","deployable":"docker://magneticio/navigation-service:latest","ports":{"port":"18090/http"},"environment_variables":{"MONGODB_PORT_27017_TCP_ADDR":"$mongodb.host","MONGODB_PORT_27017_TCP_PORT":"$mongodb.ports.port"},"constants":{},"dependencies":{"mongodb":{"name":"mongodb"}}},"scale":{"cpu":0.1,"memory":128.0,"instances":1},"routing":{"weight":100,"filters":[]},"servers":[{"name":"e61c74c8-484d-4ce8-85fc-f8c3f27b4abc_navigation.b443303a-40f7-11e5-9157-56847afe9799","host":"172.31.2.13","ports":{"18090":31322},"deployed":true}],"dependencies":{"mongodb":"mongodb"},"dialects":{"marathon":{"cmd":"export PORT=18090 && /navigation-0.6/bin/navigation"}}}],"routes":{"18090":33003},"dialects":{}},"redis":{"services":[{"state":{"name":"ReadyForUndeployment","started_at":"2015-08-13T14:48:06.555-07:00"},"breed":{"name":"redis","deployable":"docker://redis:latest","ports":{"port":"6379/tcp"},"environment_variables":{},"constants":{},"dependencies":{}},"scale":{"cpu":0.1,"memory":128.0,"instances":1},"routing":{"weight":100,"filters":[]},"servers":[{"name":"e61c74c8-484d-4ce8-85fc-f8c3f27b4abc_redis.3aaddd87-40fb-11e5-9157-56847afe9799","host":"172.31.2.11","ports":{"6379":31496},"deployed":false}],"dependencies":{},"dialects":{}}],"routes":{"6379":33005},"dialects":{}},"mongodb":{"services":[{"state":{"name":"ReadyForUndeployment","started_at":"2015-08-13T14:48:06.555-07:00"},"breed":{"name":"mongodb","deployable":"docker://mongo:latest","ports":{"port":"27017/tcp"},"environment_variables":{},"constants":{},"dependencies":{}},"scale":{"cpu":0.1,"memory":128.0,"instances":1},"routing":{"weight":100,"filters":[]},"servers":[{"name":"e61c74c8-484d-4ce8-85fc-f8c3f27b4abc_mongodb.ad123729-40f7-11e5-9157-56847afe9799","host":"172.31.2.13","ports":{"27017":31210},"deployed":true}],"dependencies":{},"dialects":{"marathon":{"cmd":"mongod --smallfiles"}}}],"routes":{"27017":33006},"dialects":{}},"product":{"services":[],"routes":{},"dialects":{}}},"ports":{"navigation.port":"33003","cart.port":"33004","checkout.port":"33001","catalog.port":"33000","mongodb.port":"33006","redis.port":"33005","product.port":"33002"},"environment_variables":{"navigation.MONGODB_PORT_27017_TCP_PORT":"33006","catalog.NAVIGATION_PORT_18090_TCP_ADDR":"localhost","catalog.CART_PORT_18100_TCP_PORT":"33004","navigation.MONGODB_PORT_27017_TCP_ADDR":"localhost","catalog.PRODUCT_PORT_18080_TCP_PORT":"33002","checkout.CART_PORT_18100_TCP_PORT":"33004","product.MONGODB_PORT_27017_TCP_ADDR":"localhost","catalog.CART_PORT_18100_TCP_ADDR":"localhost","checkout.CART_PORT_18100_TCP_ADDR":"localhost","catalog.CHECKOUT_DESIGN":"standard","catalog.PRODUCT_PORT_18080_TCP_ADDR":"localhost","checkout.MONGODB_PORT_27017_TCP_ADDR":"localhost","product.MONGODB_PORT_27017_TCP_PORT":"33006","catalog.NAVIGATION_PORT_18090_TCP_PORT":"33003","cart.REDIS_PORT_6379_TCP_PORT":"33005","catalog.SHOP_PORT_8080_TCP_ADDR":"localhost","checkout.MONGODB_PORT_27017_TCP_PORT":"33006","catalog.SHOP_PORT_8080_TCP_PORT":"33001","cart.REDIS_PORT_6379_TCP_ADDR":"localhost"},"constants":{},"hosts":{"checkout":"localhost","catalog":"localhost","cart":"localhost","navigation":"localhost","product":"localhost","mongodb":"localhost","redis":"localhost"}}%
```

**Comment by tnolet** [comment] 2015-08-14 07:44
Hi Bernd,

we have two issue with regard to deleting as far as we know. 

deleting does not work because env variables linger after partial delete (solved in 0.7.10)
https://github.com/magneticio/vamp/issues/272

deleting does not work when special characters (@) are in the blueprint (working on it)
https://github.com/magneticio/vamp/issues/310

Is this possibly one of the causes?

Also, deleting using the API is kinda different than other API's. We require you to specify in the body of the delete what you want to delete. Please see: http://vamp.io/documentation/api-reference/deployments/#delete-a-deployment-using-a-blueprint

**Comment by zutherb** [comment] 2015-08-14 07:50
@tnolet sry i did see the issues. Where is the best place to create an issue? Every time in the vamp repository?

**Comment by tnolet** [comment] 2015-08-14 07:52
@zutherb well, we look at all repo's, but we compile a release from issues only in the main Vamp repo. This way people don't have to look around multiple repos and it easier to get an overview. We'll just close this one and reference it once we have a fix and put it into a release.

**Comment by dragoslav** [comment] 2015-10-09 14:35
both magneticio/vamp#272 and magneticio/vamp#310 are already closed

**Closed** 2015-10-09 14:34 UTC
